# Generated by Django 5.1.4 on 2025-01-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_division_klass_classname_orders_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='speciesRose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.typerose'),
        ),
    ]
