# Generated by Django 5.1.4 on 2025-01-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_typerose_species_speciesrose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typerose',
            options={'verbose_name': 'Типы роз', 'verbose_name_plural': 'Типы роз'},
        ),
    ]
