# Generated by Django 5.1.4 on 2025-01-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_alter_typerose_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popular_rose/'),
        ),
    ]
