# Generated by Django 5.1.4 on 2025-01-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_typerose_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.species'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='division',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='genus',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sort',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sort',
            name='subspecies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.subspecies'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
