# Generated by Django 5.1.4 on 2025-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0006_sort_species_alter_classname_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsKingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Характеристика царства',
                'verbose_name_plural': 'Характеристики царства',
            },
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Пример типов растений', 'verbose_name_plural': 'Примеры типов растений'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип растений', 'verbose_name_plural': 'Типы растений'},
        ),
    ]
