# Generated by Django 5.1.4 on 2025-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0007_characteristicskingdom_alter_example_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genus',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sort',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subspecies',
            name='descriptionBig',
            field=models.TextField(blank=True, null=True),
        ),
    ]
