# Generated by Django 5.1.4 on 2025-01-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0008_classname_descriptionbig_division_descriptionbig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='genusSpeciesRoses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genusSpeciesRoses', to='flower.typerose'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='flower.division'),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='flower.orders'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genus', to='flower.family'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='className',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderClass', to='flower.classname'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flower.division'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortSpecies', to='flower.species'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='subspecies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortSubspecies', to='flower.subspecies'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='flower.genus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='speciesRose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciesRoses', to='flower.typerose'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecies', to='flower.species'),
        ),
    ]
