# Generated by Django 5.1.4 on 2025-01-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0009_genus_genusspeciesroses_alter_classname_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='genusSpeciesRoses',
        ),
    ]
