# Generated by Django 5.1.4 on 2025-01-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_remove_genus_genusspeciesroses'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerose',
            name='genusRose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genusRoses', to='flower.genus'),
        ),
    ]
